name: "Update packages"
cmd: "yarn upgrade"
sh: true,
targets:
  Angular production mode build:
    cmd: "node-minify --compressor clean-css --input src/queuescript.css --output src/queuescript.min.css && node-minify --compressor uglify-es --input src/backgroundscript.js --output src/backgroundscript.min.js && node-minify --compressor uglify-es --input src/queuescript.js --output src/queuescript.min.js && ng build --prod --build-optimizer"
    sh: true,
  Angular developer mode build:
    cmd: "ng build"
    sh: true,
  Angular developer mode build(with compression):
    cmd: "node-minify --compressor clean-css --input src/queuescript.css --output src/queuescript.min.css && node-minify --compressor uglify-es --input src/backgroundscript.js --output src/backgroundscript.min.js && node-minify --compressor uglify-es --input src/queuescript.js --output src/queuescript.min.js && ng build"
    sh: true,
