name: "Update packages"
cmd: "yarn upgrade"
sh: true,
targets:
  Angular production mode build:
    cmd: "ng build --prod --build-optimizer"
    sh: true,
  Angular developer mode build:
    cmd: "ng build"
    sh: true,
