variables:
  DOCKER_DRIVER: overlay2

image: maalni/maalni.gitlab.io:latest

stages:
  - build
  - tag

cache:
  paths:
  - node_modules/

build:
  stage: build
  before_script:
  - yarn
  script:
  - ng build --prod --build-optimizer
  only:
  - master
  artifacts:
    paths:
    - dist/

tag:
  stage: tag
  script:
    - curl --request POST --header "PRIVATE-TOKEN:$apikey" --data-binary "tag_name=$(cat src/manifest.json | jq -r '.version')&ref=master&release_description=[crunchysync_latest.zip](https://gitlab.com/maalni/crunchysync/-/jobs/artifacts/master/download?job=build)\r\n\r\n$(cat releasenotes.txt)" "https://gitlab.com/api/v4/projects/maalni%2Fcrunchysync/repository/tags"
  only:
    - master
