variables:
  DOCKER_DRIVER: overlay2

image: maalni/maalni.gitlab.io:latest

stages:
  - build

cache:
  paths:
  - node_modules/

build:
  stage: build
  before_script:
  - yarn
  script:
  - ng build --prod --build-optimizer
  only:
  - master
  artifacts:
    paths:
    - dist/

tag:
  stage: tag
  script:
    - curl --request POST --header "PRIVATE-TOKEN: $apitoken" -data "tag_name='v6'&ref='master'&message='[crunchysync_test.zip](https://gitlab.com/maalni/crunchysync/-/jobs/artifacts/master/download?job=build)'"
  only:
    - master
